### ISSUE TITLE
Build Front page and few modifications 

### ISSUE THREAD

**Issue by rahul-n18** [rahul-n18/Student-Library#1]
I have created this Repository which is set to help hundred's of student's.

I Just need your Ideas on how we can Implement this.
Once Check the Repo and You can fork it.

Ill Immediately PR/MR if you have a good solution.

you can create your own issue and give me a solution.

**Comment by harshxtanwar** [comment]
hello @rahul-n18, I read the read.me file. I can start with making atleast the first HTML, CSS page of the web application which will include a header page containing options of (explore library, what's new in tech?, roadmaps to machine learning, dsa, etc)

**Comment by harshxtanwar** [comment]
> hello @rahul-n18, I read the read.me file. I can start with making atleast the first HTML, CSS page of the web application which will include a header page containing options of (explore library, what's new in tech?, roadmaps to machine learning, dsa, etc)

can I get assigned to an issue with this task ?

**Comment by rahul-n18** [comment]
@harshxtanwar Sorry for the late response.

I'll assign you this Issue and modify It's Title.

But I need 2 things In return
1. Start this repo so others can see it.
2. Please Give an Idea if an app is developed what would you want in that.

Please update your forked repo.

Ps: Thank you in Advance

**Comment by harshxtanwar** [comment]
Thankyou for assigning me this issue. I will start working on the home page and make a pull request.

Here are some of my ideas:

1) I was thinking that we can have a whole database for books with different topics and the student could chose his favorite topic, we will make a library for the student with books of those topics only.

2) we can make a newsletter which students can subscribe to and we can send them weekly emails regarding some tech updates  in general.

3)  In the future, we can make a login signup page and maintain the states of different users.

**Comment by Tasneem-I** [comment]
@harshxtanwar 

Hey, I would be working on developing a resource list for frontend development and categorising it. I just wish to discuss how we can coordinate as you would be working on the website while I would take care of the frontend roadmap and resources category

**Comment by harshxtanwar** [comment]
hello @Tasneem-I you can connect with me on discord and we can discuss over there 

liomesssss#8040

**Comment by harshxtanwar** [comment]
@Tasneem-I I have just created a pull request, view the code after it gets merged and text me on discord to work more on it
