### ISSUE TITLE
All important sites for DSA/CP/Dev etc

### ISSUE THREAD

**Issue by UltimateDip** [rahul-n18/Student-Library#104]
I want to add a file where all the important and popular sites will be present so that a beginner can have access to all the sites that are people using to learn that specific skill. People can add more sites after that also

**Comment by sakshi025** [comment]
/assign this repo to me please
I want to add a picture containing important sites for the resources of dsa,cp

**Comment by UltimateDip** [comment]
> /assign this repo to me please I want to add a picture containing important sites for the resources of dsa,cp

After adding the file, you can upload the pictures.

**Comment by sakshi025** [comment]
@UltimateDip can u update me after adding the file

**Comment by UltimateDip** [comment]
@sakshi025  Just now I submitted PR. [pr link](https://github.com/rahul-n18/Student-Library/pull/108#issue-1401898170)

**Comment by rahul-n18** [comment]
hello Admin here

Thank you for your Interest in this Repo but,
before that Please read ReadMe File, you need to understand that we are going to build a platform which will help student's in Learning, So with this Issue Please Provide me an Idea how and what we can Implement, what a student needs.

### Please upload resources if you have
If you can do this Ill Assign this with Hacktoberst tag.

Happy Hacking

**Comment by UltimateDip** [comment]
For learning purposes only I want to add this. As a student, we don't have much time to waste searching for the best sites to practice DSA questions, or we don't have much time to participate in every CP site every contest, so I want to add a file which will consider the most used sites, so that student's don't need to waste any time and directly they can jump to practice or learning and hence improved efficiency.

**Comment by UltimateDip** [comment]
e.g. If someone is preparing for SDE interviews then leetcode, interviewbit etc are best.

**Comment by rahul-n18** [comment]
Hello @UltimateDip please understand that I can merge your PR but it goes against Hactoerfest.

I hope you understand and I dont want you to get the wrong Idea please add moe resources I would love to merge your PR.

**Comment by UltimateDip** [comment]
> Hello @UltimateDip please understand that I can merge your PR but it goes against Hactoerfest.
> 
> I hope you understand and I dont want you to get the wrong Idea please add moe resources I would love to merge your PR.

@rahul-n18 
First of all I'm **not** doing this for **hacktoberfest**. I'm new to open source and I want to start contributing. In the readme, I saw
> You are welcome to make your first contribution to this repo.
Therefore, I want to contribute and then update it whenever I found any new resources.
Secondly, I think this repo is excluded from hacktoberfest already,

**Comment by sakshi025** [comment]
Is this repo excluded from hacktobefest

??

**Comment by UltimateDip** [comment]
@sakshi025 yes.
![image](https://user-images.githubusercontent.com/68418035/194736246-582cc18f-5f8d-4694-a06e-a20f70f7db38.png)

![image](https://user-images.githubusercontent.com/68418035/194736255-2c5f5780-71a0-4aa1-8874-0d0e6ba22bef.png)
