### ISSUE TITLE
Add CONTRIBUTING.md file 

### ISSUE THREAD

**Issue by anshulsoni4** [rahul-n18/Student-Library#11]

**Comment by rahul-n18** [comment]
Do You want me to Assign this to you?

**Comment by anshulsoni4** [comment]
@rahul-n18 yes please

**Comment by anshulsoni4** [comment]
@rahul-n18 Thankyou

**Comment by rahul-n18** [comment]
I need few customization in this.

**Comment by anshulsoni4** [comment]
yes, let me know

**Comment by rahul-n18** [comment]
1. I want to add a Appropriate License to this Repo.
2. I need to Have Contributors Title as Kings.
    The Reason why I want the name Kings Because Each and everyone who is Working on it to help 100's out there.
 Hope you get my point.

But I need 2 things In return

1.Star this repo so others can see it.
2.Please Give an Idea if an app is developed what would you want in that.

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by rahul-n18** [comment]
@anshulsoni4 any updates

**Comment by anshulsoni4** [comment]
will complete in some time 

> @anshulsoni4 any updates

**Comment by jyotika6221** [comment]
Hey is the issue closed or can i work on it? Please reply it can be my first pr.

**Comment by anshulsoni4** [comment]
> Hey is the issue closed or can i work on it? Please reply it can be my first pr.

sure you can work :)

**Comment by jyotika6221** [comment]
@anshulsoni4 ok but @rahul-n18 needs to assign it to me.

**Comment by rahul-n18** [comment]
Happy Hacking
