### ISSUE TITLE
This repo has been excluded from hacktoberfest

### ISSUE THREAD

**Issue by sumitkr2000** [rahul-n18/Student-Library#134]
![Screenshot (396)](https://user-images.githubusercontent.com/100675296/194759068-7755304b-0e8e-4723-8cff-b7762308eb44.png)

**Comment by vishaaal** [comment]
lol thanks for informing others

**Comment by rahul-n18** [comment]
@sumitkr2000 @vishaaal we have contacted the Admin team to understand the Issue here.
but the reason you are contributing for this repo matters a lot cause, we will be helping a lot of students by guiding and literally handing down them road map
