### ISSUE TITLE
Create a Suitable Brand Kit for this Repo

### ISSUE THREAD

**Issue by rahul-n18** [rahul-n18/Student-Library#14]
### Create a Suitable Brand Kit for this Repo

Create a Suitable Brand kit for this Repo, so we can add in the Read.me file

But I need 2 things In return

1.Star this repo so others can see it.
2.Please Give an Idea if an app is developed what would you want in that.

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by dharmikjethva30** [comment]
I would like to take this issue. But can you please clarify that what you mean by "Suitable Brand Kit" and you expect suct thing for this repo.

**Comment by ayush4345** [comment]
I will be contributing to this issue.but I need some clarification regarding "suitable brand kit",and 
What you expect from us

**Comment by Tasneem-I** [comment]
A brand kit involves a logo, name, a suitable list of fonts(around 3-4) and theme colors(4-6) that are visually appealing

**Comment by dharmikjethva30** [comment]
please assign it to me. Also tell me the format I should submit.

**Comment by rahul-n18** [comment]
@dharmikjethva30 @ayush4345 

It's as @Tasneem-I  have mentioned
 In short for us to define what exactly we are building a Brand kit is Very helpful.

you can create these even in Canva but you should have understanding how exactly will this help other's in future.

a2a: the reason for writing suitable is because we have not yet created a complete project so a Discussed brand kit would be better.

**Comment by rahul-n18** [comment]
@ayush4345  @dharmikjethva30  I can assign both of you this task as it needs bit of discussion,
if you are fine with it. or else I can assign to anyone

**Comment by Tasneem-I** [comment]
A brand kit involves a logo, name, a suitable list of fonts(around 3-4) and theme colors(4-6) that are visually appealing. 

Also, after finalizing you would need to add it to the readme file

**Comment by dharmikjethva30** [comment]
> @ayush4345  @dharmikjethva30  I can assign both of you this task as it needs bit of discussion,
> if you are fine with it. or else I can assign to anyone

Do the best that seems to you , would be happy to working together

**Comment by rahul-n18** [comment]
Happy Hacking

Dont forget to Star and Update fork

**Comment by ayush4345** [comment]
[Canva brand kit](https://www.canva.com/learn/how-to-build-a-brand-kit/) 
Check this,is this what u want?

**Comment by rahul-n18** [comment]
@ayush4345  Yup that would be Good.
are you willing to Work on this?

**Comment by dharmikjethva30** [comment]
please assign , i am ready for it

**Comment by rahul-n18** [comment]
I have already
