### ISSUE TITLE
I want to fix some type error and refactor the Readme file.

### ISSUE THREAD

**Issue by Devbysteph** [rahul-n18/Student-Library#16]
I want to fix some grammatical error on the readme file, please assign to me.

Thank you.

**Comment by rahul-n18** [comment]
Please read ReadMe File, you need to understand it mainly not about editing a HTML page.

We are going to build a platform which will help student's in Learning, So with this Issue Please Provide me an Idea how and what we can Implement, what a student needs.
Please upload resources if you have.

then you can create an Issue with your Idea.

If you can do this Ill Assign this with Hacktoberst tag.

Happy Hacking
