### ISSUE TITLE
I want to add idea for programs student can participate 

### ISSUE THREAD

**Issue by Devbysteph** [rahul-n18/Student-Library#17]
I want to contribute an idea that student can search for programs and opportunities they can participate in. Most time students are not informed of the opportunities available to them. I believe if we have a section where student can get a list of opportunities and programs they can participate in it will help them alot.

Please assign this to me.

**Comment by rahul-n18** [comment]
Sure Please create your Idea with a Name and add your Ideas there.
If you have resources please make sure to Add there.

Two things you have to do before that are:

1.Star this repo so others can see it. :star:
2.Please Give an Idea if an app is developed what would you want in that. :bulb:

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by jyotika6221** [comment]
Hey is the issue closed or can i work on it? Please reply it can be my first pr.

**Comment by Devbysteph** [comment]
Hi @jyotika6221 you can work on this for your first PR. I'll unassign myself and contribute in coming time. @rahul-n18 please assign this issue to @jyotika6221

**Comment by jyotika6221** [comment]
thank you so much @Devbysteph . Please assign me this task @rahul-n18
