### ISSUE TITLE
CSS fault in the footer

### ISSUE THREAD

**Issue by InquisitiveMe15** [rahul-n18/Student-Library#21]
Screenshot of the same.

<img width="949" alt="image" src="https://user-images.githubusercontent.com/85685489/193797942-aeb49985-9f5c-4a99-982a-bfe64bae9527.png">

**Comment by InquisitiveMe15** [comment]
Please assign this issue to me and label it as **hactoberfest**.

Thank you :)

**Comment by JawHawk** [comment]
I can work on this issue, kindly assign it to me.

**Comment by rahul-n18** [comment]
Yes surely I can assign this to you, 
before that Please read ReadMe File, you need to understand it mainly not about editing a HTML page.

We are going to build a platform which will help student's in Learning, So with this Issue Please Provide me an Idea how and what we can Implement, what a student needs.
Please upload resources if you have.

If you can do this Ill Assign this with Hacktoberst tag.

Happy Hacking
