### ISSUE TITLE
CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by TechSpiritSS** [rahul-n18/Student-Library#27]
I would like to Add `CODE_OF_CONDUCT.MD` file for this repo.

**Comment by rahul-n18** [comment]
Yes Ill Assign You, but Do it b4 9Pm Ill be modifying Some Things

Two things to Do before
1.Star this repo so others can see it. ⭐
2.Please Give an Idea if an app is developed what would you want in that. 💡

Please update your forked repo so I can merge

Ps: Thank you in Advance
