### ISSUE TITLE
UI and UX design

### ISSUE THREAD

**Issue by Morbius00** [rahul-n18/Student-Library#28]
<img src="https://img.shields.io/badge/hacktoberfest-2022-blueviolet" alt="Hacktober Badge"/>

## UI and UX 

Want to change the UI and UX design for your active github page student-library website.
please assigned me this work
regards,

**Comment by rahul-n18** [comment]
Two things to Do before
1.Star this repo so others can see it. ⭐
2.Please Give an Idea if an app is developed what would you want in that. 💡

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by Morbius00** [comment]
hey @rahul-n18 put the hactober fest lable plz

**Comment by rahul-n18** [comment]
hello @Morbius00 Ill adding hacktoberfest tag.

here are the few changes I need

1. The Nav Bar looks doesn't match with things we are building, so change few name title such as what'new, call us and news letter, add something related to Repo
![Screenshot (57)](https://user-images.githubusercontent.com/64891042/193998786-a8c38fb2-6519-4be1-9036-7ced03bdb7a5.png)

2. Make this student library responsive for all devices
![Screenshot (56)](https://user-images.githubusercontent.com/64891042/193999236-f1f57f52-5048-4c40-8eb3-f233c6888798.png)

3. Remove this Crap (someone just uploaded an entire template here so many things are just unwanted)
![Screenshot (55)](https://user-images.githubusercontent.com/64891042/193999422-5c20776d-90f9-49f2-98d5-d6434e08bfcf.png)

4. Here can you rename as Contributors and change the Photos of some Contributors
![Screenshot (54)](https://user-images.githubusercontent.com/64891042/193999689-ebba22fe-9dc7-445e-8bff-5771693a2caa.png)

5. Remove this page
![Screenshot (53)](https://user-images.githubusercontent.com/64891042/193999879-88279e96-8f86-46bd-ac4c-3490e1231ffa.png)

6.  Here add about Aim or what this repo serves.
![Screenshot (52)](https://user-images.githubusercontent.com/64891042/194000035-408cdf69-4498-4af6-bc64-4e9f27e0a5d6.png)

7. Finally Make changes to UI/UX to look more appealing.

star this repo so others can see and update your forked repo.

Happy Coding

**Comment by Morbius00** [comment]
well I need a little time for but I will do it for sure

**Comment by rahul-n18** [comment]
Sure take your Time, but Please try to resolve all

**Comment by Morbius00** [comment]
Hope you like it   :)
