### ISSUE TITLE
feat: adding scroll animation

### ISSUE THREAD

**Issue by superiorsd10** [rahul-n18/Student-Library#30]
Hey! I want to add scroll animation to the website, that'll be looking really cool. 
Here's the demonstration of what it'll be looking like.

https://user-images.githubusercontent.com/92971894/193838831-83db800c-558b-4f23-b20a-07f7d4c3df0f.mp4

Please assign me this issue.

**Comment by rahul-n18** [comment]
Ill assign you this Task Please Update your current repo and that Student Library is Overlapping.
Two things to Do before
1.Star this repo so others can see it. ⭐
2.Please Give an Idea if an app is developed what would you want in that. 💡

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by superiorsd10** [comment]
@rahul-n18 
1. Done 👍🏽
2. I think it should have all the books, and a student should be able to add the book he/she wants to read to the wishlist. New books should be added regularly. Students can also upload their notes on this app so that others can see them, it's gonna help others.

**Comment by rahul-n18** [comment]
All the Best Happy Coding

**Comment by superiorsd10** [comment]
@rahul-n18 Thank You :) I've made a PR to this issue. Please review it, and Happy Hactoberfest!

**Comment by rahul-n18** [comment]
I Just checked your PR, 

> ill assign you this Task Please Update your current repo and that Student Library is Overlapping.

this Issue is Not solved

**Comment by superiorsd10** [comment]
@rahul-n18 I've resolved that 'Student Library' text overlapping.
![SCR-20221004-sqx](https://user-images.githubusercontent.com/92971894/193857331-28de37ff-dd84-45c8-8815-9956a7eb9408.png)
