### ISSUE TITLE
Fix style of header in responsive

### ISSUE THREAD

**Issue by emepuchades** [rahul-n18/Student-Library#32]
Fix the header in the responsive and lower the font size so that the responsive menu is not under the title of the web

![Captura de Pantalla 2022-10-04 a las 16 24 02](https://user-images.githubusercontent.com/100128850/193845766-fd9cdf62-68e1-4a30-b3b5-f4b3a34b507e.png)
![Captura de Pantalla 2022-10-04 a las 16 24 13](https://user-images.githubusercontent.com/100128850/193845773-051b3193-3c65-44d8-9c54-7d0ff25ef106.png)

**Comment by vardhan0604** [comment]
can you assign me this

**Comment by rahul-n18** [comment]
Yes surely I can but before that Please read ReadMe File, you need to understand it mainly not about editing a HTML page.

We are going to build a platform which will help student's in Learning, So with this Issue Please Provide me an Idea how and what we can Implement, what a student needs.
Please upload resources if you have.

If you can do this Ill Assign this with Hacktoberst tag.

Happy Hacking
