### ISSUE TITLE
Cyber security webpage

### ISSUE THREAD

**Issue by Tasneem-I** [rahul-n18/Student-Library#34]
Found the learn-computer-security.md guide and absolutely loved it. Its well-structured, captivating, concise and interesting.

I think it would be great to create a webpage for it.

**Comment by rahul-n18** [comment]
@Tasneem-I the webpage is just for a demo purpose but the actual project will be different so no need to add that I guess

**Comment by Tasneem-I** [comment]
Hey, I'm very curious about what your vision is? I understood that you are planning on having book resources available, maybe as an app. 

But what's the rough outline?

**Comment by rahul-n18** [comment]
My Idea is build a Platform(it may be web/app) that will have a library/resources for students all at one place. let me give you an example, If I wanna Learn Dsa using c++ i just search here DSA c++ and I'm served with the resources that is uploaded by our Open Source members.
Lets Assume i need a book and I search it using Api we can fetch them the copyright free books or connect them to google books which has almost every book
I hope I was able to make you understand please feel free to ask questions

**Comment by rahul-n18** [comment]
feel free to connect and exchange Ideas.

discord: https://discord.com/invite/mMqXKSVsAK
