### ISSUE TITLE
Can I add Java Fundamental Cheatsheet 

### ISSUE THREAD

**Issue by nihal-soni** [rahul-n18/Student-Library#37]
This will be very beneficial for beginner

**Comment by rahul-n18** [comment]
Yes Please create a separate folder and make sure it is helpful to others.

before that do these

1.Star this repo so others can see it.
2. If you have an Idea please add it on Idea Folder.

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by nihal-soni** [comment]
I have forked it  already

**Comment by nihal-soni** [comment]
Hey , 
I'm Nihal 
And I have created a pull request....
@rahul-n18

**Comment by rahul-n18** [comment]
surely Ill merge It

**Comment by rahul-n18** [comment]
dont forget to star

**Comment by nihal-soni** [comment]
but I Haven't got mail from Hacktoberfest 22 @rahul-n18

**Comment by rahul-n18** [comment]
what mail?

**Comment by rahul-n18** [comment]
I have added the responsible labels

**Comment by nihal-soni** [comment]
Thanks 
Now it is showing.

**Comment by rahul-n18** [comment]
good
