### ISSUE TITLE
Create library api

### ISSUE THREAD

**Issue by spykelionel** [rahul-n18/Student-Library#42]
Create an API using Nodejs, MongoDB, and Express

**Comment by spykelionel** [comment]
@spykelionel can start effectively on this, once the db entities have been discussed

**Comment by rahul-n18** [comment]
I had an Idea.
Can you make an API which fetches things from another page so it's easy to access.

![API](https://user-images.githubusercontent.com/64891042/193911616-93cf4c8b-4d0c-4ed5-b0f2-40c50e359e66.png)

Ill be leaving a Flow which you can easily understand.

**Comment by spykelionel** [comment]
All good @rahul-n18

**Comment by spykelionel** [comment]
I guess you mean from the front end right? Although my issue is clearly specific to backend

**Comment by rahul-n18** [comment]
Im thinking about both

**Comment by spykelionel** [comment]
That's not bad. A single module will do for the frontend.

**Comment by rahul-n18** [comment]
Actually I would love to discuss further on this,
can you hop on Discord to Continue about this.

**Comment by rahul-n18** [comment]
Discord:  rahul_alldaynew#3221

**Comment by rahul-n18** [comment]
sure @SahilAnower join discord we can discuss

**Comment by Rinshin-Jalal** [comment]
> sure @SahilAnower join discord we can discuss

Am also interested in this project
