### ISSUE TITLE
To add functionality to social media buttons present in the "meet our team"

### ISSUE THREAD

**Issue by Arun9739** [rahul-n18/Student-Library#43]
- There are some social media buttons prsesnt in the "Meet our team"
- After clicking the button it doesn't redirect us to the desired page.
- So I want to make it to go to the respected social media websites.

**Screenshots** :

![image](https://user-images.githubusercontent.com/84305637/193902135-764ac571-29e9-405e-ae6c-a4f6b732f80f.png)

**Comment by Arun9739** [comment]
Please assign me this issue under Hacktoberfest

**Comment by rahul-n18** [comment]
hello @Arun9739 I understand but before that Please read ReadMe File, you need to understand it mainly not about editing a HTML page.

We are going to build a platform which will help student's in Learning, So with this Issue Please Provide me an Idea how and what we can Implement, what a student needs.
Please upload resources if you have.

If you can do this Ill Assign this with Hacktoberst tag.

Happy Hacking

**Comment by rahul-n18** [comment]
Ill be closing Issue
