### ISSUE TITLE
I can add some resource link for the students of 9-12

### ISSUE THREAD

**Issue by i-am-yuvi** [rahul-n18/Student-Library#48]
I can add some very good resource link for the students of 9-12

**Comment by rahul-n18** [comment]
I would love to hear you out,
Could you elaborate?

**Comment by i-am-yuvi** [comment]
I have cleared some competitive exams and I can help by providing some quality study materials which I used to use while preparing for exams. Eg. HC Verma for physics,etc

**Comment by rahul-n18** [comment]
Ill assign you this work

**Comment by i-am-yuvi** [comment]
Sure sure @rahul-n18
