### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by Wingysam** [rahul-n18/Student-Library#5]
What is the plan for complying with copyright law?

**Comment by rahul-n18** [comment]
@Wingysam 
I'll be honest with you I want to make this available for everyone,
But if you have worked on Open-source you know there must be Good Implemented Copywrite Law which will protect works of people who are contributing to this, So if you have understood my word's above you know what exactly to Implement.

But I need 2 things In return
1. Start this repo so others can see it.
2. Please Give an Idea if an app is developed what would you want in that.

Please update your forked repo.

Ps: Thank you in Advance

**Comment by rahul-n18** [comment]
@Wingysam Do you want me to assign this to you?

**Comment by Wingysam** [comment]
I mean if you're making a library, you can't just give out books for free. Do you intend to link to places to buy books if they are still copyrighted? How is this different than for example goodreads? If you intend to violate copyright law, what differentiates this from libgen?

**Comment by rahul-n18** [comment]
> I mean if you're making a library, you can't just give out books for free. Do you intend to link to places to buy books if they are still copyrighted? How is this different than for example goodreads? If you intend to violate copyright law, what differentiates this from libgen?

@Wingysam I get what you are telling but try to understand this we are not just building only a Book library, cuz there are lot of those out there. But we will be Implementing It in the App.

But as you say we cannot directly distribute the books for free. So we have to have a brainstorming around this.

But I promise you we can make this possible, cuz I believe in People who love's coding and Open-source.
And So we can Help Many students out there.

**Comment by rahul-n18** [comment]
@Wingysam you can add a copyright/licence under some limitations

**Comment by Tasneem-I** [comment]
@rahul-n18 

Hey, it is difficult to make entire books for free but we can maybe make use of summarizing. For ex., we can make our own list showcasing notes we took on a particular book and it won't come under copyright infringement

**Comment by rahul-n18** [comment]
@Tasneem-I  YES that may be Possible.
We can Integrate Google Books Api in future to work on this.
