### ISSUE TITLE
Resources for AI/ML Enthusiasts

### ISSUE THREAD

**Issue by YashM246** [rahul-n18/Student-Library#50]

**Comment by YashM246** [comment]
@rahul-n18 I can add some Resources and Links for people who are new and want to learn more about Machine Learning Algorithms and such.

**Comment by rahul-n18** [comment]
Surely but before that
 
1.Star this repo so others can see it.
2. Make a separate folder for this

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by YashM246** [comment]
So, I have starred this repo.
Just so we are on the same page,
Ill fork this repo and create a new folder in which I'll have to add the resources and links.
Then call a pull request?

Sorry this might be a basic question but I am new to Hacktoberfest. Thanks again!

**Comment by rahul-n18** [comment]
I have Merged your Current Resource but can you add more, because it feels littlle.

Hoping for your response

**Comment by YashM246** [comment]
@rahul-n18 Yes I will keep adding as I find more and more resources!

Thanks for merging!
