### ISSUE TITLE
Can I add pdf book ?

### ISSUE THREAD

**Issue by sajjad-njr** [rahul-n18/Student-Library#54]
I see there is a folder of books that cover different pdf books. I want to add some books, Can I ?

**Comment by rahul-n18** [comment]
Yes you can but it must be copyright free book

**Comment by rahul-n18** [comment]
before that do these

1.Star this repo so others can see it.
2. If you have an Idea please add it on Idea Folder.

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by Mayank-Sharma17** [comment]
@rahul-n18 can I add a pdf book I have 2 to 3 pdfs for java and DSA concepts for easy understanding.
