### ISSUE TITLE
I want to add ML books list

### ISSUE THREAD

**Issue by TheLegendVilva** [rahul-n18/Student-Library#61]
I will like to add resources related to ML. I have a list of open source websites which will be helpful for students starting with or are in their intermediate stage on their journey to master Machine Learning. Please assign it to me and tag it hacktober.

**Comment by rahul-n18** [comment]
Sure Please Go on, ill be assigning you this Task.

before that do these

1.Star this repo so others can see it.
2. Add resources to Respective Folders

Please update your forked repo so I can merge

Ps: Thank you in Advance
