### ISSUE TITLE
fix footer header

### ISSUE THREAD

**Issue by Dun-sin** [rahul-n18/Student-Library#62]
The "Student Library" header overflows

![image](https://user-images.githubusercontent.com/78784850/194257540-be9ef405-bb78-4f69-b0a6-95c2c9823f05.png)

**Comment by rahul-n18** [comment]
before that do these

1.Star this repo so others can see it.
2. If you have an Idea please add it on Idea Folder.

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by Dun-sin** [comment]
fixing it doesn't hurt tho, but okay
