### ISSUE TITLE
Unified Border radius

### ISSUE THREAD

**Issue by Dun-sin** [rahul-n18/Student-Library#63]
The border radius for `sign up` isn't unified around the button

![image](https://user-images.githubusercontent.com/78784850/194257801-a72c1365-93b5-4373-9d38-56ed2a33a4cb.png)

**Comment by rahul-n18** [comment]
Hello @Dun-sin  happy to hear you are Interested in Contributing to this Repo.

before that Please read ReadMe File, you need to understand it mainly not about editing a HTML page.

We are going to build a platform which will help student's in Learning, So with this Issue Please Provide me an Idea how and what we can Implement, what a student needs.
Please upload resources if you have.

If you can do this Ill Assign this with Hacktoberst tag.
