### ISSUE TITLE
add some JAVA books

### ISSUE THREAD

**Issue by sushrutlekurwale** [rahul-n18/Student-Library#67]
I want to add some popular java programming books which can help students cover their fundamentals

**Comment by rahul-n18** [comment]
please make sure those are copyright free

before that do these

1.Star this repo so others can see it.
2. If you have an Idea please add it on Idea Folder.

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by jyotika6221** [comment]
Hey is the issue closed or can i work on it? Please reply it can be my first pr.
