### ISSUE TITLE
Want to add two most popular DSA sheet pdf to placement preparation. 

### ISSUE THREAD

**Issue by sb-decoder** [rahul-n18/Student-Library#69]
Please assign it to me

**Comment by rahul-n18** [comment]
Thank you for your Interest In this Repo.
before that do these

1.Star this repo so others can see it.
2. If you have an Idea please add it on Idea Folder.

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by Ashish-242** [comment]
I want to contribute towards it can you assign it to me

**Comment by rahul-n18** [comment]
Can you create a new issue and make sure to

1.Star this repo so others can see it.
2. If you have an Idea please add it on Idea Folder.

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by rahul-n18** [comment]
Thank you for your Contribution

**Comment by jyotika6221** [comment]
Hey is the issue closed or can i work on it? Please reply it can be my first pr.

**Comment by sb-decoder** [comment]
I already added striver and Fraz's DSA sheet , if you want to add another one then create a new issue and get assignment from maintainer.
