### ISSUE TITLE
Any Idea's are Welcome

### ISSUE THREAD

**Issue by rahul-n18** [rahul-n18/Student-Library#7]
Just go through this Repository and understand about this Project and you can submit your Ideas.

**Comment by mak650650** [comment]
Idea as pull request

**Comment by mak650650** [comment]
Or issue

**Comment by sudhir512kj** [comment]
@mak650650 I can add some openly available resource links for students of all levels here. Please assign me this issue

**Comment by rahul-n18** [comment]
@mak650650 can you create a new issue so where you can give your Ideas 

 I would love to merge your PR.

Any Modifications Are welcome.

But I need 2 things In return

1.Start this repo so others can see it.
2.Please Give an Idea if an app is developed what would you want in that.
Please update your forked repo.

Ps: Thank you in Advance

**Comment by rahul-n18** [comment]
@sudhir512kj  I'll be Assigning you this work.
You can add resource link for all levels.

I will repeat again, I need 2 things In return

1.Start this repo so others can see it.
2.Please Give an Idea if an app is developed what would you want in that.
Please update your forked repo.

Ps: Thank you in Advance

**Comment by Xenador77** [comment]
My ideas for the app: 
- Include soft skills and tips for job-seekers 
- Google calendar integration (or in app calendar with events that can be exported). The calendar could be populated with events like hacktober, upcoming conferences, any ongoing (usually holiday themed) discounts on courses/learn-to-code platforms/TryHackMe, CTFs, and 30 days of code type challenges.

**Comment by rahul-n18** [comment]
That's Actually a good Idea
