### ISSUE TITLE
DSA Books 

### ISSUE THREAD

**Issue by Simply-Sujal** [rahul-n18/Student-Library#71]

**Comment by Simply-Sujal** [comment]
yes i can do this work , and one request give tag of hacktoberfest to it .

**Comment by Simply-Sujal** [comment]
Can you please hactoberfest tag to it ?

**Comment by rahul-n18** [comment]
Thank you for Contributing to this Repo😊

please Star this repo so it can reach so many Students in need

**Comment by Simply-Sujal** [comment]
Can you tell me why i am getting this error ?

$ git clone https://github.com/rahul-n18/Student-Library.git
Cloning into 'Student-Library'...
remote: Enumerating objects: 934, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 934 (delta 11), reused 3 (delta 1), pack-reused 896
Receiving objects: 100% (934/934), 661.30 MiB | 3.93 MiB/s, done.
Resolving deltas: 100% (266/266), done.
error: invalid path 'GRE Material/GRE Renaissance /.DS_Store'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by rahul-n18** [comment]
First fork this repo and then try to clone it.

Hope this helps.

**Comment by Mayank-Sharma17** [comment]
hey, @rahul-n18 can you assign me. this can be my first pr <3
