### ISSUE TITLE
DevOps resources folder

### ISSUE THREAD

**Issue by Maaz-Code** [rahul-n18/Student-Library#78]
Hey there, I want to create a folder in this repository dedicated to DevOps and its resources. I will also add a few links from where people can learn. Also, others can also then contribute to it with more resources. Kindly assign this to me.

**Comment by rahul-n18** [comment]
sure ill assign you this,

before that do these

1.Star this repo so others can see it.
2. If you have an Idea please add it on Idea Folder.

Please update your forked repo so I can merge

Ps: Thank you in Advance
