### ISSUE TITLE
Favicon missing

### ISSUE THREAD

**Issue by sanvi0071** [rahul-n18/Student-Library#79]

**Comment by rahul-n18** [comment]
I would love to Add but before that Please read ReadMe File, 
you need to understand it mainly not about editing a HTML page.

We are going to build a platform which will help student's in Learning, So with this Issue Please Provide me an Idea how and what we can Implement, what a student needs.
Please upload resources if you have.

If you can do this Ill Assign this with Hacktoberst tag.

Happy Hacking
