### ISSUE TITLE
Add some resources for functional programming

### ISSUE THREAD

**Issue by muskanbararia** [rahul-n18/Student-Library#80]
Can add resources for functional programming, what it is and how to approach using haskel etc.
Would want to work on it under hacktoberfest

**Comment by rahul-n18** [comment]
Sure but please create separate folder and all the resource/road map or books which may help many students.

before that do these

1.Star this repo so others can see it.
2. If you have an Idea please add it on Idea Folder.

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by rahul-n18** [comment]
Ill be adding Hacktoberfest Label 

Happy Hacking
