### ISSUE TITLE
Priority Queues for Placements

### ISSUE THREAD

**Issue by utkarsh006** [rahul-n18/Student-Library#81]
- Want to contribute an article over Priority Queues/ Heaps into your repository.
- The article will cover how to study this topic for the Interviews.
- The article will contain the list of the top curated questions on this topic.
- Kindly assign me this issue under hacktoberfest.

**Comment by rahul-n18** [comment]
Sure I can @utkarsh006 thank you for your Interest in this repo, it will help a lot of students.

before that do these

1.Star this repo so others can see it.
2. If you have an Idea please add it on Idea Folder.

Please update your forked repo so I can merge

Ps: Thank you in Advance
