### ISSUE TITLE
showing cycles of placement

### ISSUE THREAD

**Issue by Swastik200** [rahul-n18/Student-Library#85]
a rough sketch of detailed placement rounds....hope i will be assigned

**Comment by rahul-n18** [comment]
Sure Ill be assign you this with hacktoberfest label.

before that do these

1.Star this repo so others can see it.
2. If you have an Idea please add it on Idea Folder.

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by Akash-moon** [comment]
Please assign it to me under hacktoberfest22.

**Comment by Swastik200** [comment]
Sir I will do this today itself ....

**Comment by Swastik200** [comment]
Thank u
Is it OK to work tomorrow na as network is very slow sir

**Comment by hitcodemann** [comment]
hey @rahul-n18 can u assign this to me?

**Comment by Swastik200** [comment]
Plz assign
