### ISSUE TITLE
Cheatsheets for WEB DEVELOPMENT

### ISSUE THREAD

**Issue by aditi10701** [rahul-n18/Student-Library#87]
CHEAT SHEETS for web development can be added to the web developer section consisting of a brief roadmap to prepare for placements and complete information about MERN STACK projects and brief over view of cheat sheets of HTML,CSS,JAVASCRIPT. 
I am interested to work on this issue kindly assign me the same.

**Comment by rahul-n18** [comment]
sure you can

before that do these

1.Star this repo so others can see it.
2. If you have an Idea please add it on Idea Folder.

Please update your forked repo so I can merge

Ps: Thank you in Advance
