### ISSUE TITLE
Adding Python books

### ISSUE THREAD

**Issue by TomerSHA** [rahul-n18/Student-Library#89]
I have a few books about using python in different fields (such as ciphers, math and automation.

**Comment by rahul-n18** [comment]
sure feel free to add and create a separate folder.

before that do these

1.Star this repo so others can see it.
2. If you have an Idea please add it on Idea Folder.

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by ruturaj-gh** [comment]
can you assign it to me
