### ISSUE TITLE
Learn Frontend Page

### ISSUE THREAD

**Issue by Tasneem-I** [rahul-n18/Student-Library#9]
@rahul-n18 
Hey, I think we can categorise the website into various parts like frontend, backend, cyber security, data science etc., 

More importantly, instead of trying to create tutorials we can make it as resources list that showcases what resources would be good (HTML, CSS, JS, Bootstrap, Tailwind CSS, React etc., for frontend)with categories like crash course, full detailed courses and explain minimum stuff to learn to build what sort of projects,(ex: quick explanations listing what elements of html we would use for a blog etc.,)as there are lots of how-tos but it's hard to determine good resources according to our needs 

I would like to specifically take care of finding resources for HTML, CSS, Bootstrap and structuring Frontend page so that it is easier to access. 

We can also make a programming language categories. 

Lemme know if I can work on making the HTML resources page first! 

And if it's alright if I could work on it, could you add the hacktoberfest label too?

**Comment by rahul-n18** [comment]
@Tasneem-I 
I Like your Idea to categories things.
I would love to hear more about it and see what it comes out. 

So I will be Assigning this task to you and add hacktoberfest label😅. 

But once clarify with @harshxtanwar  because even he's working on the same page.
Issue #1 .

But I need 2 things In return

1.Start this repo so others can see it.
2.Please Give an Idea if an app is developed what would you want in that.
Please update your forked repo.

Ps: Thank you in Advance

**Comment by rahul-n18** [comment]
Happy Hacking

**Comment by Tasneem-I** [comment]
Also, I was actually working on a simple project website showcasing resources I found(the project is mainly for displaying on portfolio) so there would be a lot of similarities between both of the websites 'learning Frontend' part, so I hope you won't mind. 

I wouldn't be actually hosting that project but mainly keep it as example to showcase. I hope it isn't a problem

**Comment by rahul-n18** [comment]
I actually would not mind that but Keep in Mind we are building this for everyone out there in world.

**Comment by Tasneem-I** [comment]
Of course, it's so exciting to create something thinking about how impactful it would be. 

On that note, does this project have a domain name and other web hosting technicalities?
