### ISSUE TITLE
Change BEST DIGITAL LIBRARY EXPERIENCE image

### ISSUE THREAD

**Issue by heyvats21** [rahul-n18/Student-Library#90]
In this page its the jpeg image i want to make its background transparent so that it can look much better than before.
![image](https://user-images.githubusercontent.com/81029204/194686361-a25466c0-fe38-4b9a-a8c5-ee0ce462c039.png)

Please assign it under Hactoberfest .

**Comment by rahul-n18** [comment]
Thank you for your Interest in this repo but,
before that Please read ReadMe File, you need to understand it mainly not about editing a HTML page.

We are going to build a platform which will help student's in Learning, So with this Issue Please Provide me an Idea how and what we can Implement, what a student needs.
Please upload resources if you have.

If you can do this Ill Assign this with Hacktoberst tag.

Happy Hacking
