### ISSUE TITLE
Styling issues in the footer

### ISSUE THREAD

**Issue by SpywarePersues** [rahul-n18/Student-Library#91]
![image](https://user-images.githubusercontent.com/97043346/194686891-54a669c8-d885-4760-a2b0-ea5650f02762.png)

**PLEASE MAY  I GET ASSIGNED FOR THIS ISSUE?**

**Comment by rahul-n18** [comment]
Thank you for your Interest in this Repo but,
before that Please read ReadMe File, you need to understand it mainly not about editing a HTML page.

We are going to build a platform which will help student's in Learning, So with this Issue Please Provide me an Idea how and what we can Implement, what a student needs.
Please upload resources if you have.

If you can do this Ill Assign this with Hacktoberst tag.

Happy Hacking
