### ISSUE TITLE
full stack web dev roadmap

### ISSUE THREAD

**Issue by Muthulakshimi** [rahul-n18/Student-Library#93]

**Comment by rahul-n18** [comment]
Thank you for your Interest in this Repo but,
before that do these

1.Star this repo so others can see it.
2. If you have an Idea please add it on Idea Folder.

Please update your forked repo so I can merge

Ps: Thank you in Advance

**Comment by Muthulakshimi** [comment]
@rahul-n18 On it! thanks for mentioning the steps :D
I think its taking a little more data than usual while cloning thats why I couldnt finish the pr

**Comment by rahul-n18** [comment]
sure 

Happy Hacking

**Comment by jyotika6221** [comment]
Hey, can you please assign this issue to me. It can be my first pr.

**Comment by rahul-n18** [comment]
Hello @jyotika6221 as Its already assigned you need to wait 1 day more to assign it to you

**Comment by jyotika6221** [comment]
Ok, I shall wait.

**Comment by ruturaj-gh** [comment]
hey i can do this , can you assign it to me
